services:
  # Development backend (FastAPI with reload)
  backend:
    profiles: ["dev"]
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    environment:
      - AUTH_EXCLUDE_PATHS=/docs,/redoc,/openapi.json,/health,/auth,/api/auth/
    volumes:
      - ./backend:/app
    networks:
      - golfdaddy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Development frontend (Vite dev server)
  frontend:
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=/api/v1
      - CHOKIDAR_USEPOLLING=true
      - DOCKER_ENV=true
    restart: unless-stopped
    networks:
      - golfdaddy-network

  # Production-like single service (builds frontend and serves via Gunicorn)
  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - golfdaddy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  golfdaddy-network:
    driver: bridge
