app = "golfdaddy-brain"
primary_region = "iad"
swap_size_mb = 512

[build]
  dockerfile = "Dockerfile"

[env]
  UVICORN_WORKERS = "2"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/health"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
