services:
  - type: web
    name: brain
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    dockerBuildArgs:
      - VITE_SUPABASE_URL
      - VITE_SUPABASE_ANON_KEY
      - VITE_API_BASE_URL
    envVars:
      - fromGroup: brain-secrets