services:
  - type: web
    name: brain-api
    env: docker
    plan: starter
    numInstances: 2
    healthCheckPath: /health
    dockerfilePath: Dockerfile.backend-only
    envVars:
      - key: DATABASE_URL
        fromGroup: brain-secrets
      - key: SUPABASE_URL
        fromGroup: brain-secrets
      - key: SUPABASE_ANON_KEY
        fromGroup: brain-secrets
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromGroup: brain-secrets
      - key: OPENAI_API_KEY
        fromGroup: brain-secrets
  - type: worker
    name: brain-worker
    env: docker
    plan: starter
    dockerfilePath: Dockerfile.backend-only
    startCommand: python -m backend.scripts.run_daily_analysis
    envVars:
      - key: DATABASE_URL
        fromGroup: brain-secrets
      - key: SUPABASE_URL
        fromGroup: brain-secrets
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromGroup: brain-secrets
      - key: OPENAI_API_KEY
        fromGroup: brain-secrets
  - type: cron
    name: brain-daily-batch
    schedule: "0 2 * * *"
    command: python -m backend.scripts.run_daily_analysis
    env: docker
    dockerfilePath: Dockerfile.backend-only
staticSites:
  - name: brain-frontend
    buildCommand: npm ci && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://brain-api.onrender.com
envVarGroups:
  - name: brain-secrets
