from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Commit(BaseModel):
    id: Optional[UUID] = Field(None, description="Commit record ID, generated by DB if None")
    commit_hash: str = Field(..., description="Commit hash")
    author_id: Optional[UUID] = Field(None, description="ID of the user (from users table) who authored the commit")

    # Fields from TODO
    repository_name: Optional[str] = None
    repository_url: Optional[str] = None
    branch: Optional[str] = None
    commit_message: Optional[str] = None
    commit_url: Optional[str] = None
    diff_url: Optional[str] = None
    author_github_username: Optional[str] = None
    author_email: Optional[str] = None  # This might be different from the user table email
    lines_added: Optional[int] = None
    lines_deleted: Optional[int] = None
    changed_files: Optional[List[str]] = None
    ai_analysis_notes: Optional[str] = Field(
        None, description="Raw text notes from AI analysis, potentially replaced by more structured fields below."
    )  # Potentially JSON or Text in DB - Replaced by specific fields
    complexity_score: Optional[int] = None  # From AI analysis
    risk_level: Optional[str] = None  # Could be an Enum: LOW, MEDIUM, HIGH - From AI analysis
    risk_factor: Optional[float] = None  # Numeric factor contributing to risk

    # New fields from AI commit analysis
    key_changes: Optional[List[str]] = Field(None, description="List of key changes identified by AI")
    seniority_rationale: Optional[str] = Field(None, description="Rationale for the AI-assigned seniority score")
    model_used: Optional[str] = Field(None, description="AI model used for the analysis")
    analyzed_at: Optional[datetime] = Field(None, description="Timestamp of when the AI analysis was performed")

    # New fields for EOD and Code Quality integration
    eod_report_id: Optional[UUID] = Field(None, description="ID of the linked EOD report, if any")
    eod_report_summary: Optional[str] = Field(None, description="Summary or key points from the EOD report")
    code_quality_analysis: Optional[Dict[str, Any]] = Field(
        None, description="Structured results from AI code quality analysis"
    )
    comparison_notes: Optional[str] = Field(None, description="Notes from comparing commit, EOD, and quality analysis")

    # Existing fields (ensure they remain)
    ai_estimated_hours: Optional[Decimal] = Field(None, max_digits=4, decimal_places=1)
    seniority_score: Optional[int] = None  # Moved from ai_analysis for direct access
    commit_timestamp: datetime
    created_at: Optional[datetime] = Field(None, description="Timestamp when the record was added to this DB")
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True
