version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount local data directory for SQLite database
      - ./data:/app/data
      # Mount .env file
      - ./.env:/app/.env
      # Mount the app directory for development (optional)
      # - ./app:/app/app
    environment:
      # Use SQLite for simplicity (no need for separate database)
      - DATABASE_URL=sqlite:///app/data/golfdaddy.db
      # Or use PostgreSQL if you prefer:
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/golfdaddy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL if you don't want SQLite
  # Uncomment if needed
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=golfdaddy
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   restart: unless-stopped

  # Optional: Simple nginx proxy for HTTPS
  # Uncomment if you want HTTPS
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - app
  #   restart: unless-stopped