name: Deploy to AWS EC2

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ubuntu
  EC2_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
          export DATABASE_URL="sqlite:///./test.db"
          pytest tests/unit/ -v || true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd /home/ubuntu/golfdaddy-brain/backend
            
            # Backup before update
            ./scripts/backup.sh
            
            # Pull latest changes
            git pull origin main
            
            # Rebuild and restart
            docker-compose -f docker-compose.aws.yml build
            docker-compose -f docker-compose.aws.yml up -d
            
            # Wait for health check
            sleep 10
            curl -k -f https://localhost/health || exit 1
            
            echo "✅ Deployment successful!"

      - name: Notify deployment
        if: success()
        run: |
          echo "🚀 Successfully deployed to AWS EC2"
          # Add Slack/email notification here if needed

      - name: Rollback on failure
        if: failure()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd /home/ubuntu/golfdaddy-brain/backend
            git reset --hard HEAD~1
            docker-compose -f docker-compose.aws.yml up -d
            echo "⚠️ Deployment failed, rolled back to previous version"